### ISSUE TITLE
Kafka Support?

### ISSUE THREAD

**Issue by gowtham-sai** [skale-me/skale#144]
Can Skale take the data from Kakfa topics ?

**Comment by mvertes** [comment]
A kafka connector is not yet integrated on the worker side.

However, on the master side one could consume and produce data using a nodeJS kafka connector such as [kafka-node](https://github.com/SOHU-Co/kafka-node) (other choices exist as well), and stream it to skale datasets for workers consumption using [sc.objectStream](https://github.com/skale-me/skale-engine/blob/master/doc/skale-API.md#scobjectstreaminput_stream). Keep in mind that it would a non scalable workaround.

The real solution is of course to integrate the kafka module in the worker, and map one worker per kafka partition, which would allow parallel reading or writing to kafka. Something we plan to do, after adding a cassandra connector and avro support.

**Comment by tommedema** [comment]
@mvertes what are future plans of skale? is this being actively maintained, e.g. are feature requests such as worker kafka support being considered?
