### ISSUE TITLE
Rethinkdb connector

### ISSUE THREAD

**Issue by thomasmodeneis** [skale-me/skale#148]
Hi,

For one of my customers, I m interested in making a trial with Skale.

However I need to be able to extract the data from RethinkDB and then process it further.
I read #144 but that was not clear if the solution with sc.objectStream would scale.

So, in other words, would you mind writing some how-to instructions on how-to implement the connector on the workers, so I could potentially get this sorted ? 

Thank you.

**Comment by mvertes** [comment]
Definitely, I'm starting to write a *Skale Hacker's Guide*, to describe internals, and allow contributors to provide additional connectors.

Thanks for the request

**Comment by mvertes** [comment]
Commited an initial version of a [skale hacker's guide](https://github.com/skale-me/skale-engine/blob/master/doc/skale-hackers-guide.md), work in progress here, but hope it's helpful for other developpers to review and contribute code
