### ISSUE TITLE
Async map

### ISSUE THREAD

**Issue by mateuscalza** [skale-me/skale#174]
Hello,

There is someway to use promises (or async/await) in map (and flatMap) method?
Or there is an alternative method to do it?
I need to get data from a remote API to enrich my results.

I'm really enjoying Skale, and plan to use it in production at my company.

Thank you!

**Comment by mvertes** [comment]
Hi @mateuscalza ,

Short answer: not possible right now without modifications in the engine.

Support of asynchronous functions in skale transformation methods is not so simple. It has an impact on the core engine, regarding the execution of a pipeline of transformations for  a given element of a dataset, where the presence of one or more asynchronous methods makes the whole pipeline asynchronous, thus the need to have a *promisified* pipeline (which we do not have yet).

It's not necessarily a large development effort, but it must be looked at carefully, and may require a separate execution path from synchronous pipelines, for performance reasons (avoiding repeated promise penalty in bloc processing).

In a batch compute engine, where the workers are supposed to perform their workload directly, synchronous methods are the simplest and most efficient way. I would like to have further details on your use case (existing or planned), and be sure it's worth it. Interesting problem anyway.

Thanks,
