### ISSUE TITLE
How to set up a multi-node cluster

### ISSUE THREAD

**Issue by sbansal6** [skale-me/skale#79]

**Comment by mark-bradshaw** [comment]
I believe it goes like this...

1. Clone this repo to all machines, and `npm install` to get all the node_modules setup.  
2. On the main server that you will communicate with run `bin/server.js`.  By default it will also start up local worker processes depending on the # of cpus available on the machine.  You can control this with command line params if you want, once #82 is merged.
3. On all other machines run `bin/worker.js -H <server ip> -P <server port>`

That should work.

**Comment by thomasmodeneis** [comment]
I was trying to help out documenting the multi-cluster setup, however I could not find where the code for the documentation is.
Would you mind pointing me to the right direction ?

Cheers.
